#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Leite'
        hostname: ubuntu-desktop
        username: leite
        password: '$y$j9T$AfyGtyAkHoazz9s7WXAd3.$2pdnhkhfln98/1zJxx1NuZzTajr65QaPDe0npyR6aa7'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
        - curl
        - neofetch
        - discord
        - dpkg
        - vivaldi
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    storage:
    layout:
      custom:
        - device: /dev/sda2  # Substitua pelo nome correto da partição
          wipe: true  #formata a partição
          preserve: true  # Mantém os dados existentes
          filesystem: ext4
          mountpoint: /
